### ISSUE TITLE
AppIcon

### ISSUE THREAD

**Issue by xdccrlz** [ckosmic/sm64ex-ios#10]
**Describe the bug**
Application have not icon.

**To Reproduce**
1. Build ipa
2. Install ipa
3. See "setup table"
![SM64ios](https://user-images.githubusercontent.com/29511577/138531395-075f454e-01a4-481a-9770-e3f7aa2967f4.jpeg)
tested on iOS 15.0.1, iPhone 12 Pro

**Comment by ckosmic** [comment]
Added an AppIcon generator script in 1f7f035.  Just run `brew install imagemagick` and `./appicon` and rebuild.  You may have to restart your device/respring/uicache for the icon to show up at first.
