### ISSUE TITLE
Error in wiki (Xcode)

### ISSUE THREAD

**Issue by xdccrlz** [ckosmic/sm64ex-ios#11]
**Describe the bug**
Have an error in the dir name of the command:

Downloading the project and SDL2

Create a working directory to put project files: mkdir sm64ios && cd sm64ios
Clone sm64ex-ios and SDL and set up necessary directories:
git clone https://github.com/ckosmic/sm64ex-ios.git && \
git clone https://github.com/libsdl-org/SDL.git SDL2 && \
mkdir include && \
cp -a **SDL**/include include/ && \
mv include/include include/SDL2

SDL cloned into SDL2 (git clone https://github.com/libsdl-org/SDL.git **SDL2**)
and command must be:
cp -a **SDL2**/include include/ && \
mv include/include include/SDL2

**Comment by ckosmic** [comment]
Thanks, fixed.
