### ISSUE TITLE
Game unresponsive to Controller on Apple 4KTV

### ISSUE THREAD

**Issue by sidshekar** [ckosmic/sm64ex-ios#18]
I tried connecting my Xbox one as well as the DualSense controller.

I was able to connect to the Apple 4kTV but the game doesn't respond to start, button clicks, etc. 

Basically the game is completely unresponsive to controller. Maybe another Apple 4K TV bug?

**Comment by ckosmic** [comment]
Try disconnecting your ATV remote by holding down the volume down and menu buttons for a few seconds, and then launch the game using the game controller.  I think this is an issue with SDL2 picking up the input of the remote before the game controller, making the game controller not work until you restart the game.  I'll look into this as well.

**Comment by sidshekar** [comment]
oh ya that worked. Thanks

**Comment by ckosmic** [comment]
Fixed in 8f63446.
