### ISSUE TITLE
Problem build option

### ISSUE THREAD

**Issue by xdccrlz** [ckosmic/sm64ex-ios#2]
Using EXTERNAL_DATA=1 option in the build script give an error in the python module mkzip.py no matter which gcc version is used.
Without EXTERNAL_DATA=1 option used to compile build in the sh script all good working with actual gcc version (11.2.0).
Maybe this is due to the absence of texture pack or sound bank in the res dir by default? I don't know.
Thank You very much for your incredible work! It is fantastic: sm64ios exists!

**Comment by ckosmic** [comment]
Try commenting out this line in the Makefile: 
`@echo -n > $(BASEPACK_LST)`
This caused issues for me too, but I haven't pushed this change yet
