### ISSUE TITLE
Executable Not Found when trying to run on an ATV.

### ISSUE THREAD

**Issue by mannyd209** [ckosmic/sm64ex-ios#22]
Below is the error I get:

Details

Executable Not Found
Domain: DVTMachOErrorDomain
Code: 5
Recovery Suggestion: /Users/manny/Library/Developer/Xcode/DerivedData/sm64ios-ccnmxlbiuymhkegpryinydqhsuqh/Build/Products/Debug-appletvos/sm64tvos.app is not a valid path to an executable file. Please rebuild the project to ensure that all required executables are created. Check your project settings to ensure that a valid executable will be built.
--

System Information

macOS Version 12.0.1 (Build 21A559)
Xcode 13.1 (19466) (Build 13A1030d)
Timestamp: 2021-11-18T09:24:57-08:00

**Comment by mannyd209** [comment]
Fixed it by running "MAKE CLEAN"

**Comment by scubapilot12** [comment]
I'm hitting this verbatim error when trying to build for tvOS.  Make clean doesn't seem to help.  Completely wiping out the build directory as well as starting from scratch with downloading from GitHub doesn't work either.  Any thoughts?  Running M1 MBP.

macOS Version 12.5 (Build 21G72)
Xcode 13.4.1 (20504) (Build 13F100)
