### ISSUE TITLE
Problem build Static Library-iOS

### ISSUE THREAD

**Issue by alejdelat** [ckosmic/sm64ex-ios#3]
Selected iPhone 11 as target for static library-ios and get the following error when trying to build:

No visible @interface for 'SDL_uikitviewcontroller' declares the selector 'setNeedsUpdateOfPrefersPointerLocked'

on line 332 of SDL_uikitwindow.m

Xcode 11.3

**Comment by yoshisuga** [comment]
You're using an older version of Xcode - use at least Xcode 12. The selector it's referring to is in iOS 14 (requires Xcode 12). SDL was meant to be built with the latest version of Xcode.

Also, when building libraries, it's always a good idea to choose the generic build target (Any device).

**Comment by alejdelat** [comment]
> You're using an older version of Xcode - use at least Xcode 12. The selector it's referring to is in iOS 14 (requires Xcode 12). SDL was meant to be built with the latest version of Xcode.
> 
> Also, when building libraries, it's always a good idea to choose the generic build target (Any device).

Thank you!
