### ISSUE TITLE
Not possible to build the tvOS version 

### ISSUE THREAD

**Issue by xdccrlz** [ckosmic/sm64ex-ios#31]
With the 60fps.patch, it is not possible to build the tvOS version.

**Comment by xdccrlz** [comment]
It is necessary to correct the build instructions or fix the scheme itself, since the tvOS version does not compile and does not work. 
That is, there are two ways: to use the old version of SDL2, for example, 2.0.18 from 30.11.21, or to configure work with the libraries of the current version of SDL2.

**Comment by ckosmic** [comment]
I've reverted the 60fps changes: https://github.com/ckosmic/sm64ex-ios/commit/3234ff0190262d5ec079abc836371bf408088daf
