### ISSUE TITLE
Conjunction with AltStore

### ISSUE THREAD

**Issue by xdccrlz** [ckosmic/sm64ex-ios#5]
Can’t install ipa with AltStore, only with Xcode. 
For example, Flycast ipa  installed  successfully. What does it be?

**Comment by ckosmic** [comment]
Yes, I’ve come across this issue as well.  I’ve looked into it, but it’s difficult to figure out why it doesn’t install as AltStore crashes without logs that specify a reason.  I’ll continue to get this sorted because I really want this to be installable via AltStore

**Comment by xdccrlz** [comment]
I send this problem to Riley, but he is busy with AltStore-iOS15.1b3 trouble.
I think, this behavior of AltStore is related to your kind of JIT implementation. And then you don't need AltStore at all)))

**Comment by notdido** [comment]
Tried to sideload it with Sideloadly, atleast it gave me an error log of some sort 

Sideloadly version 0.22.2, Windows 10.0, amd64
Using IPA file: C:/Users/DELL/Downloads/sm64ios_resigned.ipa: f2590f88d5f31dcac5fc28e8934febf2
Checking iOS version...
iOS version 14.7.1, will mangle bundleID
Obtaining team ID
Using team "Danail Tenev" (Individual) with id YNRA3HL6D9
Making sure device ID [redacted] is registered
Device [redacted] is already registered
Checking private key
Generating keypair
Making CSR
Signing certificate for DESKTOP-Q0MNJHF
Revoking cert for AltStore - Dido’s iPhone
Looking up app ID
Using app ID "Super Mario 64" with id C7LMGLV7NJ
Signing...
ERROR: Guru Meditation 556260@207:bede73 This does not look like valid iOS app!

**Comment by xdccrlz** [comment]
Using Sideloadly is a very good idea, i was using it too, but this solution have some aspects doing it unacceptable in comparison with XCODE method.

**Comment by notdido** [comment]
> Using Sideloadly is a very good idea, i was using it too, but this solution have some aspects doing it unacceptable in comparison with XCODE method. 

I know, just wanted to mention it gives an output the dev could work on instead of altstore's crashes with 0 output. (That error log was recieved using alt stores method of signing using sideloadly)

**Comment by ckosmic** [comment]
Support for AltStore/TrollStore has been added with this stupidly easy fix: [ba50054](https://github.com/ckosmic/sm64ex-ios/commit/ba50054b3e1cde102746a400a654862a6e2bb977)
