### ISSUE TITLE
60FPS doesn’t work and save state support

### ISSUE THREAD

**Issue by DamnBoi706** [ckosmic/sm64ex-ios#6]
**Describe the bug**
is it implemented in the current build yet? I saw you got 60FPS on Twitter video but it only run at 30FPS here on my iPhone 8 Plus here is it not powerful enough? I would love to know and also there is no option to manually save state the game could you implement that? and appreciate your work keep going!
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/72336527/136925477-8e04c406-ebe0-4d32-bacd-319e993f2844.png)
See that framerate indicator? Yeah it only run at 30FPS and yes it's accurate 
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 8Plus]
 - OS: [e.g. iOS 14.3 (taurine)]

**Additional context**

**Comment by ckosmic** [comment]
You need to apply the 60 fps patch and rebuild: `./tools/apply_patch.sh enhancements/60fps_ios.patch`

**Comment by DamnBoi706** [comment]
Thank for the reply!
